definitions:
  models.ChatMessage:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      role:
        description: user, assistant, system
        enum:
        - user
        - assistant
        - system
        type: string
      session_id:
        type: string
      updated_at:
        type: string
    required:
    - content
    - role
    type: object
  models.ChatRequest:
    properties:
      message:
        type: string
      session_id:
        type: string
    required:
    - message
    type: object
  models.ChatResponse:
    properties:
      message:
        type: string
      session_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /chat:
    post:
      consumes:
      - application/json
      description: 发送消息到AI并获取回复
      parameters:
      - description: 聊天请求
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/models.ChatResponse'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 发送聊天消息
  /chat/history/{session_id}:
    get:
      description: 获取特定会话的聊天历史
      parameters:
      - description: 会话ID
        in: path
        name: session_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/models.ChatMessage'
            type: array
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 获取聊天历史
swagger: "2.0"
